### ISSUE TITLE
クイズ（ポケモンゲット）機能　４h

### ISSUE THREAD

**Issue by chamaboy** [camp-team/prevention-project#12]
４h

- [x] 正答数に応じてポケモン（全問クリアで２体、間違いがあれば１体、全問不正解で０体）
- [x] stepper　
- [x] createPokemon(ランダムで０〜２体)
- [x] dialog

**Comment by hk95** [comment]
```ts
    for (let i = 1; i <= 151; i++) {
      if (!pokemos.i) {
        this.noGetList.push(i);
      }

      // 9
      this.noGetList.length;

      // noGetList = [1,2,3,4,5,6,7,8,10];

      
      this.noGetList[];
    }
```

**Comment by chamaboy** [comment]
全コンプリートした時に達成画面に遷移させる関数

**Comment by kkkkoki** [comment]
```const randomNumber = Math.floor(Math.random() * pokemon.length);```

**Comment by mukaida-r** [comment]
#### createPokemon(ランダムで０〜２体)
#### stepper
1日全問クリアで一体
正答数に応じてポケモン（全問クリアで２体、間違いがあれば１体、全問不正解で０体）　
送信ボタン押下
if
true3つならポケモン2体
else if
true2 false1ならポケモン1体
true1 false2ならポケモン1体
else
false3 ポケモン0体

**Comment by peyo-code** [comment]
- [ ] get-pokemon-dialog.component生成
- [ ]
