### ISSUE TITLE
クイズ画面実装　３h

### ISSUE THREAD

**Issue by chamaboy** [camp-team/prevention-project#5]

**Comment by kkkkoki** [comment]
#### 手洗いの挿絵
https://s3-ap-northeast-1.amazonaws.com/image.cozre.jp/magazine/post/717982.jpg

#### フルバージョン(いらすとや)
https://www.irasutoya.com/2020/04/blog-post_587.html

## クイズ質問
- てあらいうがいはしましたか？
- マスクはつけて外におでかけしましたか？
- 人とはなれてせいかつしましたか？
#### はい or いいえ (true or false)
